name: "tocpm CI"

on:
  pull_request:
    branches: [main, release, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Ui/Ui.ConsoleApp
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Write environment
        run: |
          printenv
      - name: Install GitVersion
        if: ${{ false }}
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Build version
        if: ${{ false }}
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml
      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
      - name: Pack
        run: dotnet pack -c Release -o package
